const app=document.getElementById('app');
const SUPABASE_URL='https://dfavqhvgimlmxynsrtwi.supabase.co';
const SUPABASE_KEY='sb_publishable_S15Cj9e7uUlksbERq4PlkQ_7xtLgBWH';
const nav=['Dashboard','Projects','Workforce','Tasks','Handoffs','QA','Activity'];
const state={view:'Dashboard',data:{},session:JSON.parse(localStorage.getItem('airi_session')||'null')};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const headers=()=>({apikey:SUPABASE_KEY,Authorization:'Bearer '+(state.session?.access_token||SUPABASE_KEY)});
async function auth(path,body){const r=await fetch(SUPABASE_URL+'/auth/v1/'+path,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error_description||data.msg||'Authentication failed');return data}
async function signIn(email,password){state.session=await auth('token?grant_type=password',{email,password});localStorage.setItem('airi_session',JSON.stringify(state.session));render();load()}
async function signUp(email,password){const data=await auth('signup',{email,password});if(data.access_token){state.session=data;localStorage.setItem('airi_session',JSON.stringify(data));render();load()}else render('Account created. Check your email if confirmation is enabled, then sign in.')}
function signOut(){state.session=null;localStorage.removeItem('airi_session');state.data={};render()}
async function q(table,select='*',limit=100){const r=await fetch(SUPABASE_URL+'/rest/v1/'+table+'?select='+encodeURIComponent(select)+'&limit='+limit,{headers:headers()});if(!r.ok)throw Error(await r.text());return r.json()}
async function load(){if(!state.session)return;for(const t of ['projects','employees','tasks','handoffs','qa_reviews','human_reviews','activity_log']){try{state.data[t]=await q(t)}catch(e){state.data[t]=[]}}render()}
function render(message=''){if(!state.session){app.innerHTML='<div class="auth"><div class="auth-card"><div class="brand"><b>AiRi</b><span>CONTROL CENTER</span></div><h1>Studio AiRi Workforce OS</h1><p>Private control center. Sign in to access workforce operations.</p><form id="authform"><input id="email" type="email" placeholder="Email" autocomplete="email" required><input id="password" type="password" placeholder="Password" autocomplete="current-password" minlength="8" required><button type="submit">Sign in</button><button type="button" id="signup">Create account</button><div id="authmsg">'+esc(message)+'</div></form></div></div>';document.getElementById('authform').onsubmit=async e=>{e.preventDefault();try{await signIn(email.value,password.value)}catch(x){authmsg.textContent=x.message}};document.getElementById('signup').onclick=async()=>{try{await signUp(email.value,password.value)}catch(x){authmsg.textContent=x.message}};return}
const d=state.data;const counts={projects:(d.projects||[]).length,employees:(d.employees||[]).length,tasks:(d.tasks||[]).length,handoffs:(d.handoffs||[]).length,qa:(d.qa_reviews||[]).length};
app.innerHTML='<div class="shell"><aside><div class="brand"><b>AiRi</b><span>CONTROL CENTER</span></div><div class="nav">'+nav.map(x=>'<button class="'+(state.view===x?'active':'')+'" data-v="'+x+'">'+x+'</button>').join('')+'</div><div class="loop">DEFINE → PLAN → GOVERN → EXECUTE → MONITOR → CORRECT → COMPOUND</div></aside><main><header><div><div class="eyebrow">STUDIO AIRI / WORKFORCE OS</div><h1>'+esc(state.view)+'</h1></div><div class="actions"><span class="user">'+esc(state.session.user?.email||'Authenticated')+'</span><button class="refresh" id="refresh">Refresh</button><button class="refresh" id="logout">Sign out</button></div></header><section class="grid">'+[['Projects',counts.projects],['Employees',counts.employees],['Tasks',counts.tasks],['Handoffs',counts.handoffs],['QA Reviews',counts.qa]].map(x=>'<div class="card stat"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('')+'</section><section class="panel">'+viewHtml(state.view,d)+'</section></main></div>';document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;render()});document.getElementById('refresh').onclick=load;document.getElementById('logout').onclick=signOut}
function viewHtml(v,d){if(v==='Dashboard')return '<div class="sectionhead"><div><h2>System status</h2><p>Authenticated live data from the Studio AiRi Supabase workforce backend.</p></div><span class="pill">AUTHENTICATED</span></div><div class="cards2"><div><b>Active work</b><p>Tasks move through specialist handoffs instead of bypassing dependencies.</p></div><div><b>Control gate</b><p>Final QA remains the delivery gate. Human review can be required before release.</p></div></div>';const map={Projects:['projects',['project_id','service','status','created_at']],Workforce:['employees',['employee_id','name','department','status']],Tasks:['tasks',['employee_id','sequence_no','task','status']],Handoffs:['handoffs',['from_employee','to_employee','qa_status','next_required_action']],QA:['qa_reviews',['project_id','status','score']],Activity:['activity_log',['actor','action','created_at']]};const [t,cols]=map[v]||['projects',['project_id','status']];return '<div class="sectionhead"><div><h2>'+v+'</h2><p>'+((d[t]||[]).length)+' records loaded.</p></div></div><div class="tablewrap"><table><thead><tr>'+cols.map(c=>'<th>'+c.replaceAll('_',' ')+'</th>').join('')+'</tr></thead><tbody>'+((d[t]||[]).slice(0,100).map(r=>'<tr>'+cols.map(c=>'<td>'+esc(r[c])+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="'+cols.length+'">No records visible to this dashboard session.</td></tr>'))+'</tbody></table></div>}
render();if(state.session)load();